name: On Push Hotfix

on:
  push:
    branches:
      - temp/hotfix

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_hotfix:
    env:
      JDK_VERSION: 17
    permissions:
      id-token: write
      contents: write
      packages: write
    runs-on: ubuntu-24.04

    steps:
      - name: 'Checkout codebase'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Run hotfix merge checks
        uses: ./mobile-android-pipelines/actions/hotfix-merge
        with:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SCREENSHOT_TEST_COMMAND: 'patterns:verifyPaparazziDebug componentsv2:verifyPaparazziDebug theme:verifyPaparazziDebug'